import type { Metadata } from "next";
import "../globals.css";
import Header from "@/app/(main)/components/Header";
import Footer from "@/app/(main)/components/Footer";
import { CartProvider } from "@/app/(store)/[store]/providers/CartContext";

export const metadata: Metadata = {
  title: "Sell Point",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <CartProvider>
          <Header />
          <main>{children}</main>
          <Footer />
        </CartProvider>
      </body>
    </html>
  );
}