import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Sell Point",
  description: "Generated by create next app",
  icons: {
    icon: "/web-app-manifest-192x192.png", // default browser tab icon
    shortcut: "/web-app-manifest-512x512.png", // optional
    apple: "/web-app-manifest-512x512.png", // for iOS home screen
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <main>{children}</main>
      </body>
    </html>
  );
}
