import type { Metadata } from "next";
import "../.././globals.css";
import Header from "@/app/(store)/[store]/components/Header";
import Footer from "@/app/(store)/[store]/components/Footer";
import { CartProvider } from "@/app/(store)/[store]/providers/CartContext";
import { notFound } from "next/navigation";

export const metadata: Metadata = {
  title: "Sell Point",
  description: "Generated by create next app",
};

async function getStoreData(storeSlug: string) {
  try {
    const res = await fetch(`http://localhost:8080/api/stores/${storeSlug}`);
    console.log("res", res);

    if (!res.ok) return null;
    return res.json();
  } catch (err: unknown) {
    if (err instanceof Error) {
      console.log("err", err.message);
    } else {
      console.log("err", err);
    }
    return null;
  }
}

export default async function RootLayout({
  children,
  params,
}: Readonly<{
  children: React.ReactNode;
  params: Promise<{ store: string }>;
}>) {
  const { store } = await params;
  const storeData = await getStoreData(store);
  console.log("storeData", storeData);

  if (!storeData) {
    notFound();
  }

  return (
    <html lang="en">
      <body>
        <CartProvider>
          <Header />
          <main>{children}</main>
          <Footer />
        </CartProvider>
      </body>
    </html>
  );
}
